config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end

  resources :bookmarks, only: [ :destroy ]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks, dependent: :destroy
    has_many :movies, through: :bookmarks
    validates :name, presence: true, uniqueness: true
    has_one_attached :photo

end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    has_many :lists, through: :bookmarks
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    before_action :set_bookmark, only: :destroy

    def new
        @bookmark = Bookmark.new
    end
    
    def create
        @bookmark = Bookmark.new (bookmark_params)
        @list = List.find(params[:list_id])
        @bookmark.list = @list
        @bookmark.save
        redirect_to list_path(@list)
    end
    
    def destroy
        @bookmark.destroy
        redirect_to lists_path
    end
    
    private
    
    def set_bookmark
        @bookmark = Bookmark.find(params[:id])
    end

    def bookmark_params
        params.require(:bookmark).permit(:comment, :movie_id, :list_id)
    end
   
end
  

app/controllers/list_controller.rb
class ListController < ApplicationController

    def index
        @list = List.all    
    end

    def show
        @list = List.find(params[:id])
    end

    def new
        @list = List.new
    end

    def create
        @list = List.new(list_params)
        @list.save
        redirect_to list_path(@list)
    end

    def Bookmarks
        @list = List.find(params[:id])
        @list.bookmarks
    end

    private

    def list_params
        params.require(:list).permit(:name)
    end

end
  

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @list = List.all    
    end

    def show
        @list = List.find(params[:id])
        @bookmark = Bookmark.new
    end

    def new
        @list = List.new
    end

    def create
        @list = List.new(list_params)
        @list.save
        redirect_to lists_path(@list)
    end

    def Bookmarks
        @list = List.find(params[:id])
        @list.bookmarks
    end

    private

    def list_params
        params.require(:list).permit(:name, :photo)
    end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/index.htm.erb
<h1>Bienvenidos a Best Video</h1>
<p>Disfruta de series Originales y exclusivas. Disfruta ahora desde la comodidad de tu hogar</p>

<ul>
    <%@bookmarks.each do |list|%>
    <li>
    <%= movie.title%>
    <%= list.comment%>
    <%= bookmark.comment%>
    </li>
    <%end%>
</ul>

app/views/bookmarks/list.html.erb
<div class= "navbar" >
<a>Revisa más títulos</a>
</div><h2><% list.movies.each do |movie| %></h2>

<ul>

  <%   @lists.each do |list| %>
    <li><%= list.name %>
     <%= link_to "delete bookmark", bookmark_path(bookmark), method: :delete %>
    </li>
  <% end %>
</ul> 

<%= link_to("volver", list_path)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list/new.html.erb
<%= simple_form_for (@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/list/show.html.erb
<h2><% @list.movies.each do |movie| %></h2>

<ul>
    <%bookmark = Bookmark.find_by(list: @list, movie: movie)%>
    <li>
    <%movie.title%>
    <br/>
    <%bookmark.comment%>
    <%= link_to "delete bookmark", bookmark_path(bookmark), method: :delete %>>
    </li>
    <%end%>
</ul>

<%=link_to("Volver", list_path)%>

<h2><%= @list.name %></h2>

<ul>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class= "navbar">
ACÁ NAVBAR
</div>
<div class= container>
  <h1>Tus Películas</h1>

  <div class= "card">
  <ul>
    <% @list.each do |list| %>
      <li>
      <%= link_to(list.name, list_path(list))%>
      
      </li>
    <% end %>
  </ul> 
  </div>

  <div>
  <%= link_to "crear categoría", new_list_path, class: "btn btn-primary" %>
  </div>
  <h2>Lo más comentado</h2>

  

    <div class="card" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
      <h5 class="card-title">Los Puentes de Madison</h5>
      <p class="card-text">En el condado de Madison, Francesca es una ama de casa recibe la visita de Robert, un fotógrafo de National Geographic.</p>
      </div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">Dirigida por Clint Eastwood</li>
        <li class="list-group-item">Drama Romántico</li>
        <li class="list-group-item">Puntuación</li>
    </ul>
    
    <div class="card-body">
      <a href="#" class="card-link">deja tu comentario</a>
      <a href="#" class="card-link">Ver ahora</a>
    </div>

</div>

app/views/lists/list.html.erb
<div class= "navbar" >
<a>Revisa más títulos</a>
</div>
<h2><% list.movies.each do |movie| %></h2>

<ul>
  <%   @lists.each do |list| %>
    <li>
    <%= list.name %>
    </li>
  <% end %>
</ul> 


<%= link_to("volver", list_path)%>

app/views/lists/new.html.erb
<div class= "navbar" >
<h2>Revisa más títulos</h2>
</div>
<div class= "container">
  <%= simple_form_for (@list) do |f| %>
  <h5><strong><%= f.input :name%></strong></h5>
  <ul>
    <li>resultado</li>

  
  <p><%= f.button :submit, class: "btn btn-primary" %>
      
    <%= link_to("Volver", lists_path)%></p>
<% end %>
</div>

app/views/lists/show.html.erb
<div class= "container">
<h2><%= @list.name %></h2>

<ul>
    <% @list.movies.each do |movie| %>

    <li>
    <%= movie.title%>
    
    <br/>
    <%= movie.bookmarks.last.comment%>
    <%= link_to "delete bookmark", bookmark_path(movie.bookmarks.first), method: :delete %>
    </li>
    <% end%>
</ul>

<%= link_to("Volver", lists_path)%>

<div>
<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :comment %>
<%= f.association :movie %>
<%= f.input :photo, as: :file %>
<%= f.submit "comentar", class: "btn btn-primary" %>


<%end%>

</div>
</div>